/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package oracle.panel;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import oracle.OracleConnection;
import oracle.model.BanDB;
import oracle.model.BanModel;

/**
 *
 * @author trilo
 */
public class TableControlPanel extends javax.swing.JPanel {
    ArrayList<BanModel> dsBans;
    OracleConnection orclConn;
    /**
     * Creates new form OrderControlPanel
     */
    public TableControlPanel() {
        initComponents();
        init();
    }
    
    private void init(){
        orclConn = new OracleConnection();
        dsBans = new ArrayList<>();
        loadListTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        table_ban = new javax.swing.JTable();

        table_ban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bàn", "Số Lượng Khách", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_ban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_banMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table_ban);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table_banMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_banMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_banMouseClicked

    private void loadListTables(){
        BanDB banDB = new BanDB(orclConn);
        dsBans = banDB.loadDSBans();
        
        DefaultTableModel tblModel = (DefaultTableModel)table_ban.getModel();
        tblModel.setRowCount(0);
        
        for (BanModel banModel : dsBans) {
            
            String trangThaiBan = "Trống";
            if(banModel.getTrangThaiBan() == 1){
                trangThaiBan = "Có Khách";
            }
            
            Object tbData[] = {banModel.getMaBan(),banModel.getSoLuongKhach(),trangThaiBan};           
            tblModel.addRow(tbData);  
        }
        
        table_ban.setRowHeight(30);
        table_ban.updateUI();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable table_ban;
    // End of variables declaration//GEN-END:variables
}
